[package]
name = "sourcetrait_almost_cli"
version = "0.0.0-1"
edition = "2024"
description = "CLI for sourcetrait_almost"
authors = ["SourceTrait <development@sourcetrait.com>"]
repository = "https://github.com/sourcetrait/sourcetrait_almost"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "almost", "cli"]

[[bin]]
name = "almost"
path = "src/main.rs"

[dependencies]
