[package]
name = "sourcetrait_lmst"
version = "0.0.0-2"
edition = "2024"
description = "lmst: the training, development, and testing tool"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_almost"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "almost", "lmst"]

[[bin]]
name = "lmst"
path = "src/main.rs"

[features]
cuda = ["sourcetrait_lib_almost/cuda"]
flash-attn = ["cuda", "sourcetrait_lib_almost/flash-attn"]

[dependencies]
burn.workspace = true
candle-core.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
sourcetrait_lib_almost.workspace = true
tokenizers.workspace = true
