[package]
name = "sourcetrait_bquest"
version = "0.0.0-4"
edition = "2024"
description = "bquest: the training, development, and testing tool"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_quest"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "quest", "bquest"]

[[bin]]
name = "bquest"
path = "src/main.rs"

[features]
cuda = ["sourcetrait_lib_quest/cuda"]
flash-attn = ["cuda", "sourcetrait_lib_quest/flash-attn"]

[dependencies]
burn.workspace = true
candle-core.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
sourcetrait_lib_quest.workspace = true
tokenizers.workspace = true
