[package]
name = "sourcetrait_quest_bridge"
version = "0.0.0-7"
edition = "2024"
description = "Era-bridge API for the SourceTrait Quest eon components"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_quest"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "quest", "bridge"]

[dependencies]
bitcode.workspace = true
futures-util.workspace = true
nu-protocol.workspace = true
nuon.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
serde.workspace = true
snafu.workspace = true
sourcetrait_cert_lib.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-util.workspace = true
