[package]
name = "sourcetrait_refquest_two"
version = "0.0.0-10"
edition = "2024"
description = "refquest: baselining of the original model and its original tools"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_quest"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "quest", "refquest", "baseline"]

[[bin]]
name = "refquest"
path = "src/main.rs"

[dependencies]
clap.workspace = true
safetensors.workspace = true
serde_json.workspace = true
snafu.workspace = true
