[package]
name = "sourcetrait_quest_core"
version = "0.0.0-8"
edition = "2024"
description = "The era-independent data and template core of the quest toolset"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_quest"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "quest", "core"]

[dependencies]
liquid.workspace = true
nu-parser.workspace = true
nu-protocol.workspace = true
nuon.workspace = true
serde.workspace = true
snafu.workspace = true

[dev-dependencies]
serde_json.workspace = true
