[package]
name = "sourcetrait_almost_compat"
version = "0.0.0-1"
edition = "2024"
description = "Compatibility layer for sourcetrait_almost"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_almost"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "almost", "compat"]

[dependencies]
